### ISSUE TITLE
Error: Unable to access jarfile unluac.jar

### ISSUE THREAD

**Issue by SnowyShiro** [TheGreatSageEqualToHeaven/LuraphDeobfuscator#2]
Whenever I try to convert it from luac to lua I get this error

**Comment by JayRain2** [comment]
shut up skid if you don' t know how to use simple unluac then you don't deserve to use this

**Comment by TheGreatSageEqualToHeaven** [comment]
You have to download unluac, you can its binary from sourceforge

https://sourceforge.net/projects/unluac/
